#!/bin/bash

#PBS -N sceneRecS1
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -m ae
##PBS -o /gpfs/data/tserre/jzhang/ColorGist/gist_color
#PBS -M zhangjun1126@gmail.com

cd /gpfs/data/tserre/jzhang/ColorGist/gist_color

# Specify the executable ...

matlab-threaded -nodisplay -nosplash <jun_gist_s1gray.m>  gs.out
# matlab-threaded -nodisplay -nosplash -r "demoRelease"
wait

  

